; Replace <YOUR_GPU_IP> with your GPU instance public IP.
; Replace llmops-workshop with the name of your SSH private key file.
[llm_workers]
<YOUR_GPU_IP> ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/llmops-workshop
